stages:
- stage: Unit
  condition: or(ne(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.Reason'], 'ResourceTrigger'))
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  # Integration Test Jobs
  - template: ../Jobs/unit.yml